pipeline {
    agent any
    
    environment {
        MY_SECRET = credentials('MY_SECRET')
    }
    stages {
        stage ('Build') {
            steps {
                echo 'Build step is executing'
            }
        }

        stage ('Test') {
            steps {
                echo 'Tests are executing'
            }
        }

        stage ('Deploy') {
            steps {
                echo 'Deploying the application'
                echo 'Environment secret can be used here like ${MY_SECRET}'
                echo 'Using the wrapper syntax for credentials'
                withCredentials([string(credentialsId: 'MY_SECRET', variable: 'THIS_SECRET')]) {
                    echo "Environment secret is using the wrapper syntax"
                }
            }
        }
    }
}