pipeline {
    agent any
    
    stages {
        stage ('Build') {
            steps {
                echo 'Build stage running'
            }
        }

        stage ('Test') {
            steps {
                echo 'Tests are executing'
            }
        }

        stage ('Deploy') {
            steps {
                echo 'Deploying the application'
            }
        }
    }
}